Seif dev
Mleyliabadi/LIPS pull request #120
Opened 2022-07-26 17:24 UTC by seifou23i

Main changes: 
- Adding different ways to ingest topo_vect feature on the LeapNet model. A notebook tutorial can be found in the getting_started folder under the name of Tutorial_ingest_topo_vect_as_feature.ipynb
- In the FC model, the tau feature can be encoded similarly to the LeapNet model (See previous notebook).
- Since the topo_vect feature is encoded the same way in both LeapNet and FC models, I merged the transform functions into the parent class: TensorflowSimulator
- Merging the code repository with the accelerated tau version
- Adding notebooks for training baselines as well as saved models  

Limits: 
-	Since Isinstance() is not working properly in keras, I commented out the code when checking the type of optimizer, so that I could pass another optimizer then adam  line 85 in TfFullyConnected class and line 105 in LeapNet class.
-	I didn’t find a generic way to save an activation function that not registered in TensorFlow (like leaky_relu) since isinstance() is not working properly, so I have made a specific condition to save tf.keras.layers.LeakyReLU  line 26 in utils file

2022-07-27 09:23 UTC, Mleyliabadi requested changes
I have some important comments in files which are suggested to be changed in this pull request. They should be treated before any integration to main branch.

2022-07-27 09:23 UTC, Mleyliabadi commented on configurations/powergrid/benchmarks/l2rpn_neurips_2020_track1_small.ini
> +attr_x = ("prod_p", "prod_v", "load_p", "load_q", "topo_vect")
Is this change has been taken into account using both FullyConnected and LeapNet augmented simulators ? 

If yes, why it has not been changed for Benchmark2 ?

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +            #TODO : exclude scaling line_status and tau features
I think this fully connected implementation should be kept as general as possible, as it will be used by other use cases. If some powergrid specific operations on data are required, they should be addressed whether in `PowerGridDataSet` class or by creating a new FullyConnected class specific to powergrids.

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/leap_net.py
> +            #     raise RuntimeError("If an optimizer is provided, it should be a type tensorflow.keras.optimizers")
There should be a check for optimizer type, that the user could not enter not accepted values for optimizer.

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net.proxy import ProxyLeapNet
why this import in FullyConnected implementation ?

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net import ResNetLayer
It is a fully connected model, and not resnet. If resnet is required, another class should be implemented by inheriting this class if it helps.

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +            #   raise RuntimeError("If an optimizer is provided, it should be a type tensorflow.keras.optimizers")
This is required, otherwise the users could enter not accepted values for an optimizer. I don't know why that could pose problems.

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_simulator.py
> +
These are very specific to PowerGrid Use case and if they are only required by LeapNet, they should be kept in Leapnet as before, otherwise if it is required also for FullyConnected, they could be added in a utils.py file. So every model could import them.

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/dataset/scaler/__init__.py
> +from lips.dataset.scaler.powergrid_scaler import PowerGridScaler
It should not be imported here, it is very specific to PowerGrid use case, and not every one is concerned (other use cases).

2022-07-27 09:23 UTC, Mleyliabadi commented on lips/utils.py
> +import tensorflow as tf
You should not import Tensorflow here, as some users may use only pytorch. We should not force the users to use both Tensorflow and Pytorch.

2022-07-27 13:38 UTC, Mleyliabadi commented
It should be precised why datasets are changed? Are there more examples than before in these new datasets ?

2022-08-05 13:32 UTC, seifou23i commented on configurations/powergrid/benchmarks/l2rpn_neurips_2020_track1_small.ini
> +attr_x = ("prod_p", "prod_v", "load_p", "load_q", "topo_vect")
This change is specific to the leapnet model. Here we want to ingest the topological vector as a main input and not as a tau_attribute. This technique is generally used when we are not primarily interested in remedial actions, but information about topological changes is beneficial to the model. That's why we use it in benchmark 1 and not in benchmark 2. 

We also give the user the option of whether or not to use this technique. That said, regardless of the benchmark, the user can use any technique he wants.

2022-08-05 13:39 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +            #TODO : exclude scaling line_status and tau features
This implementation is restored. another class named "TfFullyConnectedPowerGrid" inherited from "TfFullyConnected" is now implemented for the power grid use case

2022-08-05 13:46 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net import ResNetLayer
- A generic class "TfResNet" is implemented and inherits from "TfFullyConnected" for minimal code changes
- A Specific class "TfResNetPowerGrid" class is implemented and inherits from "TfResNet" for the PowerGrid use case

2022-08-05 13:48 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +            #   raise RuntimeError("If an optimizer is provided, it should be a type tensorflow.keras.optimizers")
Condition is restored, apparently it didn't work for me only in tensorflow version 2.9

2022-08-05 13:52 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net.proxy import ProxyLeapNet
- It was for data processing since we used LeapnetProxy functions for the topo_vect transformation

- This implementation is deprecated, we migrated these transformations in a utils.py file

2022-08-05 13:55 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_models/leap_net.py
> +            #     raise RuntimeError("If an optimizer is provided, it should be a type tensorflow.keras.optimizers")
Condition is restored,

2022-08-05 14:08 UTC, seifou23i commented on lips/augmented_simulators/tensorflow_simulator.py
> +
this implementation of the topo_vect transformation is migrated to a utils.py file. It can be used by all models, even pytorch ones. Example of use :

#instantiate the transformer only once in the training phase
if training : 
&nbsp;&nbsp;&nbsp;&nbsp; self._topo_vect_transformer = TopoVectTransformation(self.bench_config, self.params, dataset)

#get the transformed topo_vect based on topo_vect_to_tau and kwargs_tau arguments
topo_vect = self._topo_vect_transformer.transform_topo_vect(dataset)

2022-08-05 14:17 UTC, seifou23i commented on lips/utils.py
> +import tensorflow as tf
It was imported for a temporary use, it was used to save the leaky_relu activation function in json format. Now all functions passed in params are saved as a string, including activation functions

2022-08-05 14:31 UTC, seifou23i commented
> It should be precised why datasets are changed? Are there more examples than before in these new datasets ?

The dataset was used to train the models in the Neurips paper. I'm pushing the dataset here in case anyone wants to produce the same results

2022-08-05 14:55 UTC, seifou23i commented on lips/dataset/scaler/__init__.py
> +from lips.dataset.scaler.powergrid_scaler import PowerGridScaler
restored

2022-11-17 20:09 UTC, Mleyliabadi requested changes
I have putted some important comments concerning the organization of python files and modules, and also some unnecessary imports that should be removed for the generality purpose of the framework. The core of the platform should be independent of the use cases.

2022-11-17 20:09 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/leap_net.py
>  from typing import Union
LeapNet could also be move into `tensorflow_models/powergrid/` as it is specific to power grid use case

2022-11-17 20:09 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net import ResNetLayer
If any import from leap_net package is required, this implementation should be a specific implementation of fully connected architecture. We do not need ResNet layer for a fully connected architecture .

2022-11-17 20:09 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/powergrid/fully_connected_powergrid.py
> +
The `ResNetLayer` import from leap_net could be done here. Good idea to have a submodule `powergrid` for power grid use case, as you have done.

2022-11-17 20:09 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_simulator.py
> +try:
Why these imports ?! We do not need at all the leap_net package to be able to use this generic tensorflow_simulator class !

2022-11-17 20:09 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +        # Define layer to be used for the model
Change it as before without `ResNetLayer`, with regard to the above mentioned comment.

2022-12-19 09:50 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +from leap_net import ResNetLayer
For the moment, I have commented this import, to be removed completely in future.

2022-12-19 09:53 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/fully_connected.py
> +        # Define layer to be used for the model
I have commented the use of `ResNetLayer` here. However, another approach should be adopted in future like factory method, to be able to add more layers independently from this class.

2022-12-19 10:54 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/powergrid/fully_connected_powergrid.py
> +
There exists another class TfResNet which consider the ResNetLayer. No need to add this import here. See in future if any other refactoring should be done on this point !

2022-12-19 11:23 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_simulator.py
> +try:
resolved !

2022-12-19 11:24 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/leap_net.py
>  from typing import Union
done !

2022-12-19 11:24 UTC, Mleyliabadi commented on lips/augmented_simulators/utils.py
> +import numpy as np
done !

2022-12-19 11:26 UTC, Mleyliabadi commented on lips/augmented_simulators/tensorflow_models/resnet.py
> +from leap_net import ResNetLayer
done !

2022-12-19 13:34 UTC, Mleyliabadi commented
Merge PR to main after resolving all the conflicts and generalization issues.

2022-12-19 13:34 UTC, merged